// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OpenEhrProtobufMessage.proto

package com.cabolabs.openehr.comms.protobuf;

public interface OpenEhrProtobufMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cabolabs.openehr.comms.protobuf.OpenEhrProtobufMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Value can be null, number, string, bool, struct or list, like a json value
   * https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto#L51-L78
   * </pre>
   *
   * <code>map&lt;string, .google.protobuf.Value&gt; fields = 1;</code>
   */
  int getFieldsCount();
  /**
   * <pre>
   * Value can be null, number, string, bool, struct or list, like a json value
   * https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto#L51-L78
   * </pre>
   *
   * <code>map&lt;string, .google.protobuf.Value&gt; fields = 1;</code>
   */
  boolean containsFields(
      java.lang.String key);
  /**
   * Use {@link #getFieldsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.google.protobuf.Value>
  getFields();
  /**
   * <pre>
   * Value can be null, number, string, bool, struct or list, like a json value
   * https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto#L51-L78
   * </pre>
   *
   * <code>map&lt;string, .google.protobuf.Value&gt; fields = 1;</code>
   */
  java.util.Map<java.lang.String, com.google.protobuf.Value>
  getFieldsMap();
  /**
   * <pre>
   * Value can be null, number, string, bool, struct or list, like a json value
   * https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto#L51-L78
   * </pre>
   *
   * <code>map&lt;string, .google.protobuf.Value&gt; fields = 1;</code>
   */
  /* nullable */
com.google.protobuf.Value getFieldsOrDefault(
      java.lang.String key,
      /* nullable */
com.google.protobuf.Value defaultValue);
  /**
   * <pre>
   * Value can be null, number, string, bool, struct or list, like a json value
   * https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto#L51-L78
   * </pre>
   *
   * <code>map&lt;string, .google.protobuf.Value&gt; fields = 1;</code>
   */
  com.google.protobuf.Value getFieldsOrThrow(
      java.lang.String key);
}
