// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OpenEhrProtobufMessage.proto

package com.cabolabs.openehr.comms.protobuf;

public final class OpenEhrProtobuf {
  private OpenEhrProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cabolabs_openehr_comms_protobuf_OpenEhrProtobufMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cabolabs_openehr_comms_protobuf_OpenEhrProtobufMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cabolabs_openehr_comms_protobuf_OpenEhrProtobufMessage_FieldsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cabolabs_openehr_comms_protobuf_OpenEhrProtobufMessage_FieldsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034OpenEhrProtobufMessage.proto\022#com.cabo" +
      "labs.openehr.comms.protobuf\032\034google/prot" +
      "obuf/struct.proto\"\270\001\n\026OpenEhrProtobufMes" +
      "sage\022W\n\006fields\030\001 \003(\0132G.com.cabolabs.open" +
      "ehr.comms.protobuf.OpenEhrProtobufMessag" +
      "e.FieldsEntry\032E\n\013FieldsEntry\022\013\n\003key\030\001 \001(" +
      "\t\022%\n\005value\030\002 \001(\0132\026.google.protobuf.Value" +
      ":\0028\001B8\n#com.cabolabs.openehr.comms.proto" +
      "bufB\017OpenEhrProtobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.StructProto.getDescriptor(),
        });
    internal_static_com_cabolabs_openehr_comms_protobuf_OpenEhrProtobufMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_cabolabs_openehr_comms_protobuf_OpenEhrProtobufMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cabolabs_openehr_comms_protobuf_OpenEhrProtobufMessage_descriptor,
        new java.lang.String[] { "Fields", });
    internal_static_com_cabolabs_openehr_comms_protobuf_OpenEhrProtobufMessage_FieldsEntry_descriptor =
      internal_static_com_cabolabs_openehr_comms_protobuf_OpenEhrProtobufMessage_descriptor.getNestedTypes().get(0);
    internal_static_com_cabolabs_openehr_comms_protobuf_OpenEhrProtobufMessage_FieldsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cabolabs_openehr_comms_protobuf_OpenEhrProtobufMessage_FieldsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.StructProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
